version: '3.1'
name: wordpress
services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress_web
    ports:
      - 4000:80
    environment:
      WORDPRESS_DB_HOST: db_wp
      WORDPRESS_DB_USER: usr_sqlDB
      WORDPRESS_DB_PASSWORD: 123PasswordSQL
      WORDPRESS_DB_NAME: main_db
    volumes:
      - web:/var/www/html
    networks:
      - garnier
  db_wp:
    image: mysql:5.7
    restart: always
    container_name: wordpress_db
    ports:
      - 3000:3306
    environment:
      MYSQL_DATABASE: main_db
      MYSQL_USER: usr_sqlDB
      MYSQL_PASSWORD: 123PasswordSQL
      MYSQL_ROOT_PASSWORD: 123System
    volumes:
      - db:/var/lib/mysql
    networks:
      - garnier

volumes:
  web:
  db:

networks:
  garnier:
    driver: bridge
